/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU.VISTA;

import DIU.CONTROLADOR.Controlador_Acta;
import DIU.MODELO.Reunion;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefe
 */
public class Acta_Reunion extends javax.swing.JInternalFrame {

      ArrayList<Reunion> listaReuniones = new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form Acta_Reunion
     */
    public Acta_Reunion() {
        initComponents();
        setModelo();
        
    }

    
public void setModelo() {
        String[] cabecera = {"Nº","Resolucion", "Fecha y hora", "Tipo", "Observaciones"};
        modelo.setColumnIdentifiers(cabecera);
        tblReuniones.setModel(modelo);
    }
    


 public void setDatos() {
    limpiarTabla();
    int cont = 1;
    for (Reunion puntero : listaReuniones) {
        Object[] filas = new Object[modelo.getColumnCount()];
        System.out.println("--" + puntero);
        filas[0] = cont;
        filas[1] = puntero.getIdResolucion();
        filas[2] = puntero.getFechaHora();
        filas[3] = puntero.getTipoOrdinariaExtraordinaria();
         filas[4] = puntero.getObservaciones(); // Asegúrate de tener este método en tu clase Resolucion
        modelo.addRow(filas);
        cont++;
    }
    
    tblReuniones.setModel(modelo);
    txtresolucion.setText("");
    txtHorayfecha.setText("");
    txtObservacioones.setText("");
    rbttnExtra.setSelected(false); // Desmarcar el radio button Aprobado
    rbttnOdinario.setSelected(false); // Desmarcar el radio button No Aprobado
  
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BttnRegistrar = new javax.swing.JButton();
        txtresolucion = new javax.swing.JTextField();
        txtHorayfecha = new javax.swing.JTextField();
        txtObservacioones = new javax.swing.JTextField();
        rbttnOdinario = new javax.swing.JRadioButton();
        rbttnExtra = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReuniones = new javax.swing.JTable();
        bttnver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("ACTA REUNION");

        jLabel2.setText("Resolucion");

        jLabel3.setText("Fecha y Hora");

        jLabel4.setText("Tipo");

        jLabel5.setText("Observaciones");

        BttnRegistrar.setText("Registrar Reunion");
        BttnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnRegistrarActionPerformed(evt);
            }
        });

        rbttnOdinario.setText("ORDINARIO");

        rbttnExtra.setText("EXTRAUDINARIO");
        rbttnExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbttnExtraActionPerformed(evt);
            }
        });

        tblReuniones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReuniones);

        bttnver.setText("Ver resoluciones aceptadas");
        bttnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnverActionPerformed(evt);
            }
        });

        jButton1.setText("PDF ESTUDIANTE APROBADA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PDF DGC APROBADA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(BttnRegistrar))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbttnOdinario)
                                    .addComponent(rbttnExtra)
                                    .addComponent(txtHorayfecha)
                                    .addComponent(txtresolucion)
                                    .addComponent(txtObservacioones, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttnver)
                                    .addComponent(jButton2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHorayfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rbttnOdinario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbttnExtra)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtObservacioones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnver)
                    .addComponent(BttnRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbttnExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbttnExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbttnExtraActionPerformed

    private void BttnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnRegistrarActionPerformed
  
        LocalDateTime fechaHoraActual = LocalDateTime.now();
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
String fechaHoraFormateada = fechaHoraActual.format(formatter);

// Asignar la fecha y hora formateada al cuadro de texto
txtHorayfecha.setText(fechaHoraFormateada);
    int idResolucion = Integer.parseInt(txtresolucion.getText());
    String fechaHora = txtHorayfecha.getText();
    String tipoOrdinariaExtraordinaria = rbttnOdinario.isSelected() ? "ORDINARIO" : "EXTRAORDINARIO";
    String observaciones = txtObservacioones.getText();

    Controlador_Acta controlador = new Controlador_Acta();
    controlador.insertarActaReunion(idResolucion, fechaHora, tipoOrdinariaExtraordinaria, observaciones);
    setDatos();
    cargarDatos();
    }//GEN-LAST:event_BttnRegistrarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        setDatos();
        cargarDatos();
    }//GEN-LAST:event_formInternalFrameActivated

    private void bttnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnverActionPerformed
 try {
        Controlador_Acta controladorAprobadas = new Controlador_Acta();
        ArrayList<Controlador_Acta.ResolucionAprobada> resolucionesAprobadas = controladorAprobadas.obtenerResolucionesAprobadasDesdeBaseDeDatos();

        // Crear un nuevo modelo de tabla
        DefaultTableModel modeloAprobadas = new DefaultTableModel();
        String[] cabecera = {"ID Resolución", "Archivo PDF Aprobado"};
        modeloAprobadas.setColumnIdentifiers(cabecera);

        // Llenar el nuevo modelo con los datos de resoluciones aprobadas
        for (Controlador_Acta.ResolucionAprobada resolucion : resolucionesAprobadas) {
            Object[] fila = {resolucion.getIdResolucion(), resolucion.getArchivoPdfAprobado()};
            modeloAprobadas.addRow(fila);
        }

        // Establecer el nuevo modelo en la tabla
        tblReuniones.setModel(modeloAprobadas);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar las resoluciones aprobadas desde la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
        
    }//GEN-LAST:event_bttnverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       int filaSeleccionada = tblReuniones.getSelectedRow();

    if (filaSeleccionada != -1) {
String nombreArchivo = tblReuniones.getValueAt(filaSeleccionada, 1).toString();
        String rutaGuardar = "C:\\Users\\jefe\\OneDrive\\Escritorio\\PROYECTO 3RO\\Resoluciones-OSS\\src\\main\\java\\Oficio_Estudiantes\\";
        String rutaCompletaArchivo = rutaGuardar + nombreArchivo;

        try {
            java.awt.Desktop.getDesktop().open(new java.io.File(rutaCompletaArchivo));
        } catch (java.io.IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo Word.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un pedido antes de intentar abrir el Word.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblReuniones.getSelectedRow();

    if (filaSeleccionada != -1) {
String nombreArchivo = tblReuniones.getValueAt(filaSeleccionada, 1).toString();
        String rutaGuardar = "C:\\Users\\jefe\\OneDrive\\Escritorio\\PROYECTO 3RO\\Resoluciones-OSS\\src\\main\\java\\Oficio_DGC\\";
        
        
        String rutaCompletaArchivo = rutaGuardar + nombreArchivo;

        System.out.println("Intentando abrir el archivo: " + rutaCompletaArchivo);

        try {
            java.awt.Desktop.getDesktop().open(new java.io.File(rutaCompletaArchivo));
        } catch (java.io.IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo Word.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un pedido antes de intentar abrir el Word.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
     
    }//GEN-LAST:event_jButton2ActionPerformed

 
    private void limpiarTabla() {
        int a = modelo.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
    
      
    public void cargarDatos() {
    try {
        Controlador_Acta controladorReuniones = new Controlador_Acta();
        listaReuniones = controladorReuniones.obtenerResolucionesDesdeBaseDeDatos();
        setDatos();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al cargar los datos desde la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnRegistrar;
    private javax.swing.JButton bttnver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbttnExtra;
    private javax.swing.JRadioButton rbttnOdinario;
    private javax.swing.JTable tblReuniones;
    private javax.swing.JTextField txtHorayfecha;
    private javax.swing.JTextField txtObservacioones;
    private javax.swing.JTextField txtresolucion;
    // End of variables declaration//GEN-END:variables
}
